xKV_config:
  num_layers: 32
  layer_merge_impl: svd
  rank_k: 4096
  rank_v: 4096
  merge_key: true
  merge_value: false
  layer_groups:
  - layers:
    - 0
  - layers:
    - 1
  - layers:
    - 2
  - layers:
    - 3
    - 4
    rank_k: 512
    rank_v: 768
  - layers:
    - 5
    - 6
    rank_k: 512
    rank_v: 768
  - layers:
    - 7
    - 8
    - 9
    rank_k: 512
    rank_v: 768
  - layers:
    - 10
    - 11
    - 12
    - 13
    - 14
    - 15
    - 16
    rank_k: 512
    rank_v: 768
  - layers:
    - 17
    - 18
    - 19
    - 20
    - 21
    - 22
    - 23
    - 24
    rank_k: 512
    rank_v: 768
  - layers:
    - 25
    - 26
    - 27
    - 28
    - 29
    - 30
    - 31
    rank_k: 512
    rank_v: 768
